workspace:
  base: /go
  path: src/github.com/lgtmco/lgtm

pipeline:
  test:
    image: golang:1.6
    commands:
      - make deps
      - make gen_assets gen_migration
      - make test

  build:
    image: golang:1.6
    commands:
     - make test_mysql
     - make build
    when:
      event: push

  docker:
    repo: lgtm/lgtm
    tag: [latest, 1.1.0]
    when:
      branch: master
      event: push

services:
  mysql:
    image: mysql:5.6.27
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
